### ISSUE TITLE
Inconsistent plan error with `okta_profile_mapping`

### ISSUE THREAD

**Issue by sklarsa** [okta/terraform-provider-okta#1016]
### Terraform Version
```
Using okta/okta v3.22.0 from the shared cache directory
Terraform v1.0.0
```

### Affected Resource(s)

- okta_profile_mapping

### Terraform Configuration Files

```hcl
resource "okta_profile_mapping" "base_user_group" {

  source_id = data.okta_user_profile_mapping_source.user.id
  target_id = okta_app_oauth.hs.id

  mappings {
    id          = local.hs_group_attribute
    expression  = "user.${local.hs_group_attribute}"
    push_status = "PUSH"
  }

  depends_on = [
    okta_app_user_schema_property.hs_group
  ]
}

```

### Expected Behavior

There should be no error.

### Actual Behavior
The first time we ran `terraform apply`, we got this error
```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.okta-customer-tenant.okta_profile_mapping.base_user_group
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/okta/okta" produced an invalid new value for
│ .always_apply: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

In a second run though, the apply worked

**Comment by monde** [comment]
Thanks @sklarsa I will look into this.

**Comment by techjutsu-mikeb** [comment]
This also occurs with other resources; however, additional "apply" runs do not resolve the issue.
This may be a result of how Terraform processes dependencies for "depends_on" data resources since my example should be using IdP values retrieved from the Okta Org prior to executing

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.qa_idp_discovery.okta_policy_rule_idp_discovery.anywhere_rules_saml["System IDP to System SP Routing rule"] to include new values learned so far during apply, provider
│ "registry.terraform.io/okta/okta" produced an invalid new value for .idp_id: was null, but now cty.StringVal("<idp id here>").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by monde** [comment]
Glad to have that additional info @techjutsu-mikeb , thanks
