### ISSUE TITLE
Import environment

### ISSUE THREAD

**Issue by extreme4all** [okta/terraform-provider-okta#1168]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Terraform is great for new applications, but what about existing applications & configuration on the okta tenant?
I would like to have an integrated tool to export okta config & applications to terraform

**Comment by noinarisak** [comment]
Hey @extreme4all ! I totally agree, sadly this is not a gap in the Okta Provider but general gap in Terraform CLI it self. Meaning this issue exist in other providers like AWS, GCP, etc.. I label it as a  "brownfield" situation where I configured my Service/Provider via UI console but want to start using Terraform to start IaC-ing. 

Your options are either:
- Manually author all the HCLs that mirror your environment and then `terraform import ...` so you have `tfstate` file. 
- Use some open sources tooling created by the community, [terraformer](https://github.com/GoogleCloudPlatform/terraformer) (aka Reverse Terraform) and others tooling like [terraforming](https://github.com/dtan4/terraforming) (only tied to AWS).

One consideration is to voice this gap directly to HashiCorp Feature Request form at https://support.hashicorp.com/hc/en-us/requests/new, if not also on their primary github repo.https://github.com/hashicorp/terraform as GitHub Feature Request.

Resources:
https://www.terraform.io/cli/import (The documentation mention a future version could generate HCL, but I been working on Terraform since v0.12 about 3 years ago and still waiting 😅) 

It is not an answer but I hope that adds some color to your request.

**Comment by monde** [comment]
Thanks @noinarisak , great question @extreme4all . If @noinarisak's information satisfies your question please close this issue.

**Comment by monde** [comment]
Seems like the question was answered. Closing the issue, please reopen for further discussion.
