### ISSUE TITLE
Terraform import feature for okta_email_customization

### ISSUE THREAD

**Issue by ppanan33** [okta/terraform-provider-okta#1244]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add import feature for the provider okta_email_customization to import the existing email resources from okta.
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/email_customization

### New or Affected Resource(s)

- okta_email_customization

**Comment by monde** [comment]
Thanks @ppanan33 . Also marking this a bug.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-524197

**Comment by monde** [comment]
Not stale

**Comment by grumpymatt** [comment]
Did this get fixed? I'm not able to figure out how to import okta_email_customization.
 I get an error saying `Error: brand_id required to read email customization`

**Comment by monde** [comment]
Not stale

**Comment by mmartin-sdc** [comment]
terraform import does not appear to be properly implemented for this resource. I have a large number of email templates that I had to remove from the tfstate file in order to continue to manage our okta account when the api changed for how email templates are updated. Running a terraform import for this resource appears to succeed without any change in the tfstate file. support for terraform import for okta_email_customization is still desired as trying to apply a terraform resource definition for an already existing email template customization is not idempotent and results in the below error. 
`Error: failed to create email customization: the API returned an error: An email template customization for that language already exists.`

**Comment by monde** [comment]
I'm going to close this, [@samcook](https://github.com/samcook) did a bang up job on `okta_email_customization` import functionality in 
https://github.com/okta/terraform-provider-okta/releases/tag/v3.43.0

We can reopen this issue if need be.

**Comment by cjh-Ella** [comment]
> Did this get fixed? I'm not able to figure out how to import okta_email_customization. I get an error saying `Error: brand_id required to read email customization`

I also have the same issue today on Sep 5th, 2023. 

Trying to import existing email template, already identified the `brand_id`, `terraform import` command correct, importing themes with the same `brand_id` worked, only importing email templates doesn't work. 

Getting the same error 

> brand_id required to read email customization

Used both `brand_id = okta_brand.example.id` or `brand_id = okta_brand.example.brand_id`, both didn't work. I already imported the brand to Terraform as a resource.
