### ISSUE TITLE
okta_policy_mfa resource: factor enrolment inconsistent behaviour within okta_policy_mfa (required/optional/not_allowed)

### ISSUE THREAD

**Issue by angeloedades** [okta/terraform-provider-okta#1331]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.34.0
+ provider registry.terraform.io/okta/okta v3.37.0

### Affected Resource(s)

okta_policy_mfa

### Terraform Configuration Files

From:
```hcl
resource "okta_policy_mfa" "mfa_policy_<NAME REMOVED>_privileged_users" {
  name        = "MFA <NAME REMOVED> Privileged Users Policy"
  status      = "ACTIVE"
  priority    = 3
  is_oie      = false

  okta_password = {
    enroll = "REQUIRED"
  }

  okta_email = {
    enroll = "REQUIRED"
  }

  phone_number = {
    enroll = "OPTIONAL"
  }

  okta_verify = {
    enroll = "OPTIONAL"
  }

  google_otp = {
    enroll = "NOT_ALLOWED"
  }
```

To:
```hcl
resource "okta_policy_mfa" "mfa_policy_<NAME REMOVED>_privileged_users" {
  name        = "MFA <NAME REMOVED> Privileged Users Policy"
  status      = "ACTIVE"
  priority    = 3
  is_oie      = false

  okta_password = {
    enroll = "REQUIRED"
  }

  okta_email = {
    enroll = "REQUIRED"
  }

  phone_number = {
    enroll = "OPTIONAL"
  }

  okta_verify = {
    enroll = "REQUIRED"
  }

  google_otp = {
    enroll = "OPTIONAL"
  }
```

### Debug Output

Terraform will perform the following actions:

okta_policy_mfa.mfa_policy_<NAME REMOVED>_privileged_users will be updated in-place
  ~ resource "okta_policy_mfa" "mfa_policy_<NAME REMOVED>_privileged_users" {
      ~ google_otp        = {
          ~ "enroll"       = "NOT_ALLOWED" -> "OPTIONAL"
            # (1 unchanged element hidden)
        }
        # (11 unchanged attributes hidden)
    }

### Panic Output

N/A

### Expected Behavior

In the example above we set:
google_otp from NOT_ALLOWED to OPTIONAL
okta_verify from OPTIONAL to REQUIRED

### Actual Behavior

google_otp went from NOT_ALLOWED to OPTIONAL
okta_verify did not change (OPTIONAL to NOT_ALLOWED)

for okta_verify factor, we checked Okta Admin UI and it is still listing as disabled.

### Steps to Reproduce

1. Create the policy as above
2. `terraform apply`
3. Change the policy factors
4. `terraform apply`
5. Check Okta Admin UI to see some factors have not changed

### Important Factoids

1. This okta tenant is running on oktapreview.com 
6. This okta tenant has been recently upgraded to OIE, from classic
7. We set is_oie = false because there is an existing bug when is_oie = true, see reference below

### References

1. is_oie bug - https://github.com/okta/terraform-provider-okta/issues/1176

- #0000

**Comment by angeloedades** [comment]
I would like to add that this resource's behaviour has not been consistent at all. I will try another set of changes between factor enrolment states and post it here.

**Comment by nickrmc83** [comment]
I think this is probably related to [this bug with OIE and the current Terraform provider](https://github.com/okta/terraform-provider-okta/issues/1176#issuecomment-1185953920) and might be fixed by [this PR](https://github.com/okta/terraform-provider-okta/pull/1210)

**Comment by angeloedades** [comment]
@nickrmc83 thanks for that PR link - I think it will solve it.

During testing - it seems that the policy behaviour is very unreliable due to this - I know it only talks about okta_verify but I have had issues with other Okta factors too presenting the same behaviour - Okta changes it successfully but the Okta Admin UI says something different - its very inconsistent thus far.

**Comment by matthewsolly** [comment]
@angeloedades I think the problem here is related to how you are defining the factor types. The [resource documentation](https://registry.terraform.io/providers/okta/okta/latest/docs/resources/policy_mfa) states that `okta_verify`is only applicable to OIE policies, but you have created a policy with `is_oie = false` (a Classic policy). The way you define the Okta Verify factor differs between OIE and non-OIE policies.

Note: If you are on OIE, you can create both OIE and classic policies. If you are on classic engine, you can only create classic policies. 

If your tenant is on OIE, you should set `is_oie = true` to create an OIE policy. I'm not too sure if this works as an in-place switch, or if you need to recreate the whole policy. If your tenant is not on OIE and is still on the classic engine (and therefore can't support OIE policies), or you can't change the policy type to OIE, you need to define Okta Verify as two separate factors like so: 

> 
>   okta_otp = {
>     enroll = "OPTIONAL"
>   }
> okta_push = {
>     enroll = "OPTIONAL"
>   }
> 

Unfortunately at this point if you are creating an OIE policy you may run in to the bug mentioned earlier: https://github.com/okta/terraform-provider-okta/issues/1176#issuecomment-1185953920. A possible workaround mentioned in that thread is just to use a classic policy. Classic policies do still work on OIE, but you need to use the separate definition of `okta_otp` and `okta_push` I mentioned above.

**Comment by angeloedades** [comment]
@matthewsolly I will try and walk through this in a bit - the big on is_oie is an issue we are contending with. Ideally we want to represent the truth by making it true and sticking with OIE compatible factor definitions and policies. I will do some testing on this today and report back.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544023
