### ISSUE TITLE
Support for ARM builds

### ISSUE THREAD

**Issue by chrisjaimon2012** [okta/terraform-provider-okta#1370]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.8
on darwin_arm64

### Affected Resource(s)

- okta_*

### Actual Behavior

```
Provider registry.terraform.io/okta/okta v3.7.4 does not have a package
available for your current platform, darwin_arm64.
```

**Comment by monde** [comment]
Hi @chrisjaimon2012 [v3.7.4](https://github.com/okta/terraform-provider-okta/releases/tag/v3.7.4) was released December 2020. We aren't going to be able to go back port a `darwin_arm64` build artifact to that release. It looks like goreleaser started producing a `darwin_arm64` build in the [v3.11.1](https://github.com/okta/terraform-provider-okta/releases/tag/v3.11.1) release. All releases since then and including the current release [v3.38.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.38.0) support `darwin_arm64`.
