### ISSUE TITLE
since 3.42 ReadOnly Admin role isnt sufficient for data.okta_user

### ISSUE THREAD

**Issue by callum-stakater** [okta/terraform-provider-okta#1492]
Starting with 3.42 we started to get the following error after calling data.okta_user when run as an OKTA user that has the `Read Only Administrator` role which did have and logically should have sufficient permissions to query the users. 

`Error: failed to set user's roles: failed to get roles: the API returned an error: You do not have permission to perform the requested action`

This is happening during the refresh phase of both plan and apply

the sequence of data calls is constructed like:

```terraform
data "okta_group" "admins" {
  name          = "gitlab-admin"
  include_users = true
}

data "okta_group" "maintainers" {
  name          = "gitlab-maintainers"
  include_users = true
}

data "okta_group" "developers" {
  name          = "gitlab-developers"
  include_users = true
}

data "okta_group" "external" {
  name          = "gitlab-external"
  include_users = true
}

locals {
  all_users = setunion(
    data.okta_group.admins.users,
    data.okta_group.maintainers.users,
    data.okta_group.developers.users,
    data.okta_group.external.users,
    )

  all_admins      = data.okta_group.admins.users
  all_maintainers = data.okta_group.maintainers.users
  all_developers  = data.okta_group.developers.users

#HERE IS WHERE IT FAILS
data "okta_user" "all" {
  for_each = local.all_users
  user_id  = each.value
}
```

**Comment by zarko-a** [comment]
We were troubleshooting the same issue as you encountered and stumbled upon `skip_roles = true` that works around this issue. 

I found it mentioned in the release notes for 3.39
https://github.com/okta/terraform-provider-okta/releases/tag/v3.39.0

After further digging through git, I traced it down to [this PR](https://github.com/okta/terraform-provider-okta/pull/1437/files), more specifically [this line](https://github.com/okta/terraform-provider-okta/blob/1a1f93da5447f47530030b799b363396dd364335/okta/data_source_okta_user.go#L138) 
where set roles is called within `data` `okta_user` resource. 

It still feels like a weird behavior for `data` resource to try and `set` any roles. 

@monde it would be great if we could get some clarity if this was intentional and why? 

Our use case involves using read-only admin to get user attributes with Terraform.

**Comment by monde** [comment]
Sorry about that, I missed making sure #1437 had background on the change in the PR's description.

I filled in the background:

This change was made in regards of https://github.com/okta/terraform-provider-okta/issues/1208
Instead of "fixing" `admin_roles` on user potentially causing another breaking change, a new `roles` attribute was included on the `user` data source to allow the operator to see all the roles as they see fit. I see the the implementation didn't take into consideration the `skip_roles` behavior on that data source.

@duytiennguyen-okta we should fix that.

**Comment by monde** [comment]
Also, I think the error is coming off the subsequent call to `GET /api/v1/users/%v/roles` that is used to decorate the information into the `roles` attribute. @zarko-a name of that function `setRoles` is a bit off. What is occurring is that the roles from `GET /api/v1/users/%v/roles` are gathered and "set" onto the data source. It's really just a decorator of information on the data source so perhaps `setRoles` should be `decorateRoles`. Everything the user data source is doing are with `GET`s, there aren't any `PUT`s or `POST`s.

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-589530

**Comment by zarko-a** [comment]
Thanks for a quick response @monde , and the explanation.

So, to clarify, once the bug/issue is resolve **read-only** admin should be able to use `data "okta_user"` resource without any write permissions, right?  Since it's only supposed to "set" onto the TF data source.
