### ISSUE TITLE
`okta_group_rule` always fetching in `plan -refresh=false`

### ISSUE THREAD

**Issue by foo-1a** [okta/terraform-provider-okta#1791]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/okta/okta v4.5.0
```

### Affected Resource(s)

- `okta_group_rule`

### Terraform Configuration Files

to reproduce:

```hcl
terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "4.5.0"
    }
  }
}

provider "okta" {
  base_url = "okta.com"
  org_name = "<YOUR-ORG-HERE>"
  # OKTA_API_TOKEN provided from env var
}

resource "okta_group" "terraform_test_group" {
  name  = "terraform okta group ${count.index}"
  count = 10
}

resource "okta_group_rule" "terraform_test_group_rule" {
  name   = "terraform-group-${count.index}-rule"
  status = "ACTIVE"
  group_assignments = [
    okta_group.terraform_test_group[count.index].id
  ]
  expression_type       = "urn:okta:expression:1.0"
  expression_value      = "user.title == '${count.index}'"
  remove_assigned_users = true
  count                 = 10
}

```

### Debug Output

https://gist.github.com/foo-1a/813d189d21db4732edc1ba17dfaac909

### Expected Behavior

Would have expected no calls to Okta to be made and diff only to be calculated from state.

### Actual Behavior

An API call made to get state of each rule, as shown in picture (terraform traffic intercepted locally with `mitmproxy` )

![mitmproxy interception of the run](https://github.com/okta/terraform-provider-okta/assets/116576812/85900b48-5172-41bc-9f92-8093a66b44bf)

### Steps to Reproduce

- use tf file above
- `terraform init`
- `OKTA_API_TOKEN=<your_token> terraform apply` to create everything
- `OKTA_API_TOKEN=<your_token> plan -refresh=false`
to observe traffic with [mitmproxy](https://mitmproxy.org/), follow installation instructions as per linked website, trust CA locally  and run with defaults in separate terminal, then start terraform with env vars as such:

`HTTP_PROXY=localhost:8080 HTTPS_PROXY=localhost:8080 OKTA_API_TOKEN=<your_token> plan -refresh=false`

(there are sure alternatives to this, I just happened to have mitmproxy at hand)

### Important Factoids

Looking at the provider code it looks this might be intentional.
However, this behaviour is causing huge problems for us: we rely heavily on group rule automation to manage our organisation based on identity attributes, and hence created a huge number of groups.

Given that the Okta API limits are rather low, having the group rules fetching at every plan even with refresh suppressed causes us to trip the ratelimit at every plan on every PR on our Okta tf repo. This is making development near-impracticable as any small unrelated change will still trigger all the rules to trip the ratelimits (and before anyone suggests it - we _are_ working towards splitting the codebase to reduce the impact of this, but that still doesn't solve the problem entirely).

As additional context, we are using Pulumi and not Terraform directly. The `pulumi_okta` provider simply uses the terraform bridge to rely on this provider instead. `pulumi preview`, which is what we are executing on PRs, by default does the equivalent of `terraform plan -refresh=false` .

### References

Provider code that we think is causing this: https://github.com/okta/terraform-provider-okta/blob/808539dfc5096fcb0ac9cc7cfffb934a75897a28/okta/resource_okta_group_rule.go#L60 

- #0000

**Comment by exitcode0** [comment]
(I'm not from Okta, but i'll chime in to try to be helpful)
agree that this should be addressed, but in the mean time:
- have you setup `max_api_capacity` on the provider? its not perfect but it can help a bit, it will slow down plans while the provider waits for the rate limit to refresh
- you can also request increases to your Okta API rate limits via Okta support
  - something that's not well known is that Okta support can even create new rate limit buckets with the right internal approval

**Comment by foo-1a** [comment]
thanks @exitcode0, will try ask okta support about increasing ratelimits again while we wait for resolution, we were previously told this wasn't an option.
we didn't set `max_api_capacity` on the provider, but I don't think it would make a big difference for us whether we self-hold-back or just get ratelimited by API as the provider honours it and retries on its own anyway.

**Comment by tgoodsell-tempus** [comment]
This is a good catch, I'll see if I can help do a patch for this (unless Okta chimes in and wants to do it). There shouldn't be any API calls in the `CustomizeDiff` functions, since these operate on the Terraform internal lifecycles. In theory the `INVALID` check can just be done off the schema since the `refresh` phase will populate the correct data for that check.

**Comment by monde** [comment]
Confirmed CustomizeDiff is the bad actor https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_group_rule.go#L61

**Comment by monde** [comment]
I'm not even sure if `CustomizeDiff` is needed. It's been there from the beginning of this resource. The ACC tests `TestAccResourceOktaGroupRule_crud` and `TestAccResourceOktaGroupRule_invalidHandle` pass if I comment out that CustomizeDiff function.

It seems like the logic is this: Force new if the group no longer exists or the if `status` of the rule is `INVALID`. I question if this resource should be having opinions here and leave it to the operator deal with.

cc: @duytiennguyen-okta

**Comment by tgoodsell-tempus** [comment]
> I'm not even sure if `CustomizeDiff` is needed. It's been there from the beginning of this resource. The ACC tests `TestAccResourceOktaGroupRule_crud` and `TestAccResourceOktaGroupRule_invalidHandle` pass if I comment out that CustomizeDiff function.
> 
> It seems like the logic is this: Force new if the group no longer exists or the if `status` of the rule is `INVALID`. I question if this resource should be having opinions here and leave it to the operator deal with.
> 
> cc: @duytiennguyen-okta

IMO, `INVALID` I think should require a `force_new` when used in Terraform. Rules in this state can only be deleted, therefore if a user has Terraform config for it still, it's a nice feature to include to ensure it's one less thing they need to manually massage (part of the point of TF). In general, we should assume that if the config still exists in the TF file, then the user intents for that resource to exist.

**Comment by monde** [comment]
ok, I pinged our community partner contact at Hashicorp and received some advice about this situation. First, they think a better implementation of the customized diff on `status` would be:

```go
CustomizeDiff: customdiff.ForceNewIf("status", func(ctx context.Context, d *schema.ResourceDiff, meta interface{}) bool {
	return d.Get("status").(string) == statusInvalid // "INVALID"
}),
```

Noting that `-refresh=false` effectively disables the TF runtime from calling the `ReadContext` function `resourceGroupRuleRead` https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_group_rule.go#L20 . And that `-refresh=false` means "trust that nothing has changed in the remote system since my last run". Essentially, the implementation as-is overreaches by making the API call to populate `status` as you're getting that already on the last call to the `ReadContext` (perhaps during an apply, or true refresh).

I know that @foo-1a would be happy with this change. But I'd like to hear from experienced operators @exitcode0 @tgoodsell-tempus @duytiennguyen-okta

**Comment by tgoodsell-tempus** [comment]
> ok, I pinged our community partner contact at Hashicorp and received some advice about this situation. First, they think a better implementation of the customized diff on `status` would be:
> 
> ```go
> CustomizeDiff: customdiff.ForceNewIf("status", func(ctx context.Context, d *schema.ResourceDiff, meta interface{}) bool {
> 	return d.Get("status").(string) == statusInvalid // "INVALID"
> }),
> ```
> 
> Noting that `-refresh=false` effectively disables the TF runtime from calling the `ReadContext` function `resourceGroupRuleRead` https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_group_rule.go#L20 . And that `-refresh=false` means "trust that nothing has changed in the remote system since my last run". Essentially, the implementation as-is overreaches by making the API call to populate `status` as you're getting that already on the last call to the `ReadContext` (perhaps during an apply, or true refresh).
> 
> I know that @foo-1a would be happy with this change. But I'd like to hear from experienced operators @exitcode0 @tgoodsell-tempus @duytiennguyen-okta

I agree that the presented change is the "most correct" answer for updating this, as far as I'm aware.

**Comment by exitcode0** [comment]
I don't have any concerns with changing `CustomizeDiff` such that `-refresh=false` acts as expected/designed
I agree that tainting the resource if `status == INVALID` makes sense and should stay, but this seems like it belongs in the resource's `read()` function?

one thing that's not clear to me is how `okta_group_rule` interacts with `remove_assigned_users` if the user tries to set `remove_assigned_users` on a tainted resource, e.g:
1. I have a rule targeting 5 groups with `remove_assigned_users` undefined
1. One of the target groups is deleted via click-ops
1. The `okta_group_rule` is now `status == INVALID`
1. I update `remove_assigned_users` to the value that I would like it to have when Terraform deletes the now invalid rule

Does terraform:
1. Update, then delete the resource - honoring my wishes to keep or remove the users from the other 4 groups
2. Delete, then creates the new resource with the defined `okta_group_rule` value - failing to honor my wishes

It seems to me like this has to work like option 2 because updating the `status == invalid` rule would fail?

**Comment by monde** [comment]
I'm going to make this change, fyi

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-663340
