### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by joshk0** [okta/terraform-provider-okta#4]
Should articulate/terraform-provider-okta be the canonical version?

I would propose either removing this or working with the articulate folks to give them access to this repository.

Thanks.

**Comment by quantumew** [comment]
Sorry for the delay I was not watching this repo. I am now! We were hoping to release our provider as the official provider. Unfortunately, as soon as it was ready, Okta stepped in and stopped it due to "licensing issues". I agree if this gets delayed any longer this should just get deleted until we can actually go through with it. Just causing confusion at this point.

**Comment by pratikmallya** [comment]
Can we nuke this repo if its ded? Unfortunately, terraform will try to install this by default giving the appearance of a broken/unstable/old provider.

**Comment by quantumew** [comment]
CC: @cgriggs01 did we ever hear back about the blockage on this repository?

**Comment by quantumew** [comment]
I revived this topic with the interested parties a month or so ago, I will ping them and see where this is at. cc: @cgriggs01

**Comment by j0nathontayl0r** [comment]
@pratikmallya best way around it is to install the articulate okta provider as per the third-party installation guideline.

https://github.com/articulate/terraform-provider-okta/issues/317

**Comment by fatbasstard** [comment]
@quantumew Hi,

any news on the progress? Anything I can help out with perhaps? 

This "official" version of the Okta provider would make our live a lot easier, so looking forward on enabling this as the one-and-only-true Okta provider

**Comment by quantumew** [comment]
@fatbasstard @pratikmallya Sorry for the delay, I heard back on this, and it turns out Okta is not willing to rubber stamp this 😞. We instead will be included in the first iteration of the community registry. No strict timeline on that yet. Hashicorp should be removing this from their official provider registry soon.

**Comment by cgriggs01** [comment]
Change in direction. We are align with the team at Okta and @quantumew. The change will be coming soon to address the issues here and release the provider formally to releases.hashicorp.com.

**Comment by pratikmallya** [comment]
@cgriggs01 that's great news! Any idea around when that might happen (days? months?)? In the meanwhile, should new contributions continue to go to the  articulate/ version?

**Comment by quantumew** [comment]
@pratikmallya Working on getting this repo updated now (https://github.com/terraform-providers/terraform-provider-okta/pull/6). I would keep an eye on that, a release will follow shortly after that is merged. Shooting for early next week.

**Comment by noinarisak** [comment]
@quantumew @cgriggs01 I think we can close this issue, since we are almost fully migrated, minus migrating the old Issues from Articulate repo.

**Comment by noinarisak** [comment]
Closing! =)
