### ISSUE TITLE
Unable to find provider 3.11.0

### ISSUE THREAD

**Issue by ambrosy-eric** [okta/terraform-provider-okta#405]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.2

### Affected Resource(s)

- okta provider

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    okta = {
      source  = "oktadeveloper/okta"
      version = "~> 3.11.0"
    }
}
```

### Expected Behavior

Terraform finds and installs provider 3.11.0

### Actual Behavior

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
oktadeveloper/okta: no available releases match the given constraints ~>
3.11.0
```

### Steps to Reproduce

Run a `terraform init -upgrade` with a required provider that pulls the most recent provider

Or go to https://registry.terraform.io/providers/oktadeveloper/okta/latest and see that latest listed is 3.10.1

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @ambrosy-eric! Thanks for submitting this issue! 

The problem is that official Okta provider has migrated from `oktadeveloper` to `okta` namespace and thus we can not publish it to the registry without a new `gpg` key. 

The official answer from Hashicorp states:
```
We've currently going through an engineering org change. The request to transfer to `okta` namespace will hopefully be possible in just a few weeks.
```

There is always a possibility to use [in-house provider ](https://www.terraform.io/docs/cloud/run/install-software.html#in-house-providers) built from source. Basically, you clone the repo and run `go install` or download a binary from [release page](https://github.com/okta/terraform-provider-okta/releases/tag/v3.11.0) and you can use it as your main provider.

For example, here is my local terraform provider configuration:
```
├── terraform.d
│   └── plugins
│       └── my-host
│           └── me
│               └── okta
│                   └── 4.0.0                            <- version can be whatever you like
│                       └── darwin_amd64                 <- arch
│                           └── terraform-provider-okta  <- binary 
└── versions.tf
```

`versions.tf` file content:

```
terraform {
  required_providers {
    okta = {
      source  = "my-host/me/okta"                          
      version = "4.0.0"                                               <- version can be whatever you like
    }
  }
  required_version = ">= 0.13"
}
```

After that, you should run `terraform init` to make terraform use your custom provider.

**Comment by bogdanprodan-okta** [comment]
Added note [here](https://github.com/okta/terraform-provider-okta#important-note)
