### ISSUE TITLE
Maintain base profile properties like custom ones

### ISSUE THREAD

**Issue by klaushauschild1984** [okta/terraform-provider-okta#504]
Whit resource `okta_user_schema` I am able to extend the user profile with custom properties.

Is there a way to customize already existing properties like `firstName` or `lastName` to make them optional for instance?

**Comment by klaushauschild1984** [comment]
This is already supported by Okta API. See documentation https://developer.okta.com/docs/reference/api/schemas/#update-user-profile-schema-property

**Comment by bogdanprodan-okta** [comment]
Hi @klaushauschild1984! Based on this [docs](https://developer.okta.com/docs/reference/api/schemas/#user-profile-base-subschema), you can.
```
All Okta-defined Profile properties are defined in a Profile subschema with the resolution scope #base. 
You can't modify these properties, except to update permissions, to change the nullability of `firstName` 
and `lastName`, or to specify a `pattern` for login. They can't be removed.
```
You can use this as an example

```
resource "okta_user_base_schema_property" "firstName" {
  index = "firstName"
  title = "First name"
  type = "string"
  required = false
}

resource "okta_user_base_schema_property" "firstName" {
  index = "lastName"
  title = "Last name"
  type = "string"
  required = false
}
```

P. S. Currently provider requires to set `title` and `type`, but because they are immutable, `okta_user_base_schema_property` will be fixed in the future
