### ISSUE TITLE
Migration from "okta_app_user_schema" to "okta_app_user_schema_property" resources

### ISSUE THREAD

**Issue by jrummlerS24** [okta/terraform-provider-okta#587]
Hi! 

I'm facing an issue to migrate from `okta_app_user_schema` to `okta_app_user_schema_property`. 

Even when I import the previously existing `okta_app_user_schema` as the new `okta_app_user_schema_property` (via `terraform import okta_app_user_schema_property.example <app id>/<property name>`) I fail to migrate to the new resource name.

Now that wouldn't be a problem if I could just destroy and recreate the property, but that's not possible. 

Creation fails with: 
```You cannot add the attribute with the variable name 'xy' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again```

So how should this migration work? Any hint would be appreciated!

**Comment by bogdanprodan-okta** [comment]
Hi @jrummlerS24! Thanks for submitting this issue! The problem is that sometimes it takes time to remove `app_user_schema_property` (because it has to update all the users assigned to this app).
This is an example of how I did it:
1. Import the ` okta_app_user_schema_property.test `, but keep intact `okta_app_user_schema.test` (the old one).
```
terraform import okta_app_user_schema_property.test appID/myPropertyName
````
2. Copy-paste all the fields from `okta_app_user_schema.test` to `okta_app_user_schema_property.test`
3. Remove resource with deprecated name from the state 
```
terraform state rm okta_app_user_schema.test
```
4. Remove resource with old name from the `.tf` file manually.
5. Run `terraform apply` to apply the default fields.

**Comment by jrummlerS24** [comment]
Thank you!!
