### ISSUE TITLE
Error: failed to create user custom schema: json: cannot unmarshal number into Go struct field UserSchemaAttributeItems.definitions.custom.properties.items.enum of type string

### ISSUE THREAD

**Issue by ahmei0** [okta/terraform-provider-okta#706]
Getting following error

code is

```
resource "okta_user_schema_property" "user_channelId" {
  index       = "channelId"
  title       = "channelId"
  type        = "number"
  description = "channelId"
  master      = "OKTA"
  scope       = "SELF"
  user_type   = "default"
}
```

 # okta_user_schema_property.user_channelId will be created
  + resource "okta_user_schema_property" "user_channelId" {
      + description = "channelId"
      + id          = (known after apply)
      + index       = "channelId"
      + master      = "OKTA"
      + permissions = "READ_ONLY"
      + scope       = "SELF"
      + title       = "channelId"
      + type        = "number"
      + user_type   = "default"
    }

Plan: 1 to add, 1 to change, 0 to destroy.
okta_user_schema_property.user_channelId: Creating...
okta_app_oauth.ast_app_oauth: Modifying... [id=0oax7iqu1rmao3HyF3l6]
okta_app_oauth.ast_app_oauth: Modifications complete after 1s [id=0oax7iqu1rmao3HyF3l6]
╷
│ Error: failed to create user custom schema: json: cannot unmarshal number into Go struct field UserSchemaAttributeItems.definitions.custom.properties.items.enum of type string
│ 
│   with okta_user_schema_property.user_channelId,
│   on app_oauth_native.tf line 27, in resource "okta_user_schema_property" "user_channelId":
│   27: resource "okta_user_schema_property" "user_channelId" {

trace log as below
2021-10-12T08:58:15.0735379Z ---[ REQUEST ]---------------------------------------
2021-10-12T08:58:15.0735826Z POST /api/v1/meta/schemas/user/default HTTP/1.1
2021-10-12T08:58:15.0736376Z Host: alintaenergy-dev.okta.com
2021-10-12T08:58:15.0737059Z User-Agent: okta-sdk-golang/2.6.2 golang/go1.17 linux/amd64 okta-terraform/3.13.10 
2021-10-12T08:58:15.0737648Z Content-Length: 266
2021-10-12T08:58:15.0737997Z Accept: application/json
2021-10-12T08:58:15.0738665Z Authorization: SSWS ***
2021-10-12T08:58:15.0739188Z Content-Type: application/json
2021-10-12T08:58:15.0739719Z Accept-Encoding: gzip
2021-10-12T08:58:15.0739882Z 
2021-10-12T08:58:15.0740163Z {
2021-10-12T08:58:15.0740460Z  "definitions": {
2021-10-12T08:58:15.0740785Z   "custom": {
2021-10-12T08:58:15.0741110Z    "id": "#custom",
2021-10-12T08:58:15.0741475Z    "properties": {
2021-10-12T08:58:15.0741811Z     "channelId": {
2021-10-12T08:58:15.0742169Z      "description": "channelId",
2021-10-12T08:58:15.0742531Z      "master": {
2021-10-12T08:58:15.0742865Z       "type": "OKTA"
2021-10-12T08:58:15.0743176Z      },
2021-10-12T08:58:15.0743492Z      "permissions": [
2021-10-12T08:58:15.0743807Z       {
2021-10-12T08:58:15.0744131Z        "action": "READ_ONLY",
2021-10-12T08:58:15.0744502Z        "principal": "SELF"
2021-10-12T08:58:15.0744829Z       }
2021-10-12T08:58:15.0745106Z      ],
2021-10-12T08:58:15.0745418Z      "required": false,
2021-10-12T08:58:15.0745764Z      "scope": "SELF",
2021-10-12T08:58:15.0746111Z      "title": "channelId",
2021-10-12T08:58:15.0746459Z      "type": "number"
2021-10-12T08:58:15.0746756Z     }
2021-10-12T08:58:15.0747028Z    },
2021-10-12T08:58:15.0747336Z    "type": "object"
2021-10-12T08:58:15.0747632Z   }
2021-10-12T08:58:15.0747895Z  }
2021-10-12T08:58:15.0748154Z }
2021-10-12T08:58:15.0748281Z 
2021-10-12T08:58:15.0748937Z -----------------------------------------------------: timestamp=2021-10-12T08:58:15.072Z
2021-10-12T08:58:15.1406761Z 2021-10-12T08:58:15.139Z [INFO]  provider.terraform-provider-okta_v3.13.10: 2021/10/12 08:58:15 [DEBUG] Okta API Response Details:
2021-10-12T08:58:15.1407561Z ---[ RESPONSE ]--------------------------------------
2021-10-12T08:58:15.1407902Z HTTP/2.0 200 OK

**Comment by ahmei0** [comment]
FYI @bogdanprodan-okta

**Comment by bogdanprodan-okta** [comment]
@ahmei0 I guess it's because you are using the wrong version of terraform provider:
```
User-Agent: okta-sdk-golang/2.6.2 golang/go1.17 linux/amd64 okta-terraform/3.13.10
```
Try the latest one. You should see something like this:
```
User-Agent: okta-sdk-golang/2.8.0 golang/go1.17 darwin/amd64 okta-terraform/3.15.0 
```

**Comment by ahmei0** [comment]
I'm not providing any version so I assume it should take the latest one. Let me fix the version as above

**Comment by ahmei0** [comment]
Thanks @bogdanprodan-okta that worked.

While I have your attention here, I have a quick question.

A branch in git represent an environment for me which has its own authserver, apps etc. While app custom attributes are separate for each env but user profile custom attributes are common at account level. 

Those user profile attributes are being setup ( overwritten may be ?) from every branch. It is happening without any issues. What are your thoughts on this approach. Should I separate user profile attributes and run that code just once per account or its fine the way it is working now. I'm wondering if run destroy from one of the branch would it impact user profile attributes of other environment?

**Comment by bogdanprodan-okta** [comment]
If the user profile attributes are within the same org, then yes, destroying will impact them.

**Comment by ahmei0** [comment]
You reckon I should have a 'global' project for one-off org level config like enabling multi factors , user profile custom attributes etc. Is there anything else you can think of ?

**Comment by bogdanprodan-okta** [comment]
I think you can try using [#workspaces](https://www.terraform.io/docs/language/state/workspaces.html) to operate different resources.

**Comment by ahmei0** [comment]
I'm already using workspaces. A separate workspace per env. 
![image](https://user-images.githubusercontent.com/62230464/136937569-2a33785c-926c-48db-83cf-b81e0089aeee.png)
As per above screenshot dev, local and spt belong to a common org, every other org has just 1 environment.

How would workspaces help in this case? ie. dev, local and spt all are updating user profile attributes which is working fine( so my understanding on this may be wrong). Even though they are separate workspaces aren't they trying to update the same resource i.e. user profile custom attribute?

**Comment by ahmei0** [comment]
and if one of the workspace is destroyed, wouldn't it try to delete profile custom attribute ?

**Comment by ahmei0** [comment]
Somehow it is working fine atm, ie. multiple workspaces updating user profile attribute and destroying a workspace isn't impact attributes. How? may be destroy logic isn't implemented and it isn't destroying attribute on Okta while it does remove it from workspace

**Comment by bogdanprodan-okta** [comment]
I'm not sure about that, because I haven't used workspaces. Default one is enough for local testing. 
As for updating/destroying things, the provider is basically a wrapper around API to create/read/update/delete things. Thus, removing profile mapping from the org is basically a REST call. However, another workspace might just recreate it. 
@noinarisak maybe you can put some more clarity into this?

**Comment by ahmei0** [comment]
one workspace creates it first and another one just updates it instead of trying to recreate depending on how okta api works. But destroy or removal from one of the workspace should just delete it as it would send a delete api call right? but it isn't deleting makes me think delete functionality might be missing like the one we found other day

**Comment by noinarisak** [comment]
hey @ahmei0, As you may know using workspace is really about separating `tfstate` file between your SDLC environments and how Terraform knows there is going to be change to the target environment. Something like, local.oktaperview.com to dev.oktapreview.com and so on up the environment pipeline. What I find odd is the screenshot of your workspace, maybe because you are a window box, but usually, there would be the following folder structure with `terraform.tfstate.d` folder and with the workspace would contain your `tfstate` file by the workspace label. ie `dev`.

```bash
▶ tree terraform.tfstate.d
terraform.tfstate.d
├── dev
├── prd
└── uat
```

My [repo](https://github.com/noinarisak/okta-terraform-demo) which is a little outdated, still got to upgrade to TF v1.x 😅 , but it demonstrates `terraform workspace` subcommand with multiple okta environments. Just navigate to [example_multi_environment_with_workspace ](https://github.com/noinarisak/okta-terraform-demo/tree/master/example_multi_environment_with_workspace). Again maybe it is just because you are on Windows.  

Regarding the question about "one-off" org level changes. Here are possible options base on scanning the dialog with @bogdanprodan-okta :

1. One possible strategy, is to isolate the "global" configuration into a completely different repo, still using the workspace of course, but this repo does not have frequent changes compared to other repo that would contain your Apps, Groups, Policies, etc. that are more frequently being updated which keep touching the `tfstate` file. Of course, this will only make sense if there are no dependencies between, global repo vs the "services" or "business unit" level HCL files because Terraform won't be able to see `tfstate` file to get the relationship between repos since they are not sharing `tfstate` file. It really going to depend on what you structured in your HCL file and the relationship between the resources/data. I possible workaround in this case is, `output`ing to shared file that is then referenced by the repo that that has more frequent changes. 
2. Consider breaking HCL into modules. More details below
 - https://www.terraform.io/docs/language/modules/develop/index.html
 - https://learn.hashicorp.com/tutorials/terraform/module-create
 - Terraform offers a [ lifecycle/ignore_changes](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes) meta-argument, which cloud be more harmful than good but an option. 
 
The theme is controlling that `tfstate` file, basically the "separation of concern" concept to reduce impact and if you working in a team, consider remote state and locking. Hope that made sense.

**Comment by bogdanprodan-okta** [comment]
I'm closing this issue since the original problem was solved.
