### ISSUE TITLE
Terraform up a user, activate it and set password doesn't appear to work

### ISSUE THREAD

**Issue by thekbb** [okta/terraform-provider-okta#757]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.50.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/okta/okta v3.13.8
```

### Affected Resource(s)

- `okta_user`

### Terraform Configuration Files

```hcl
resource "okta_user" "test_108" {
  email      = "test-108@example.com"
  first_name = "Test"
  last_name  = "One Hundred Eight"
  login      = "test-108"
  group_memberships = [var.test_group_id]
  password          = jsondecode(data.aws_secretsmanager_secret_version.secret_name.secret_string)["test_108_password"]
  status            = "ACTIVE"
}
```

### Expected Behavior

The user is created, activated and has the password supplied.

### Actual Behavior

The plan looks good! 
```
      + password                  = (sensitive value)
```

However on apply:
```
Error: failed to update user's password: the API returned an error: Api validation failed: oldPassword.value. Causes: errorSummary: oldPassword.value: The field cannot be left blank
```

### Steps to Reproduce

terraform up a new users, setting `status = "ACTIVE"` and set a `password`

It seems this used to work? #148 seems to indicate it won't work for password policy reasons?

**Comment by bogdanprodan-okta** [comment]
Hi, @thekbb! Thanks for submitting this issue! The problem is that password for this user was set outside the terraform provider, so it doesn't know the old password. On the resource update, the provider calls the endpoint for changing the password, but because the old value for `password` is empty, the endpoint returns a validation error. I can add another `old_password` field to the resource, so it will be possible to change the password if it wasn't originally set via the provider.

**Comment by thekbb** [comment]
The password for the user isn't set, it's a brand new user - does that change things?
My goal for test users:
1. put passwords in aws secretsmanager
2. create the `okta_user`, setting it to `status = ACTIVE` with the password from secretsmanager
3. be able to log in with that user and password

So a brand new user won't have a password, I'm assuming if `old_password` is required it must be valid? or would any non-null value work?

**Comment by bogdanprodan-okta** [comment]
@thekbb I need to look into that and understand the flow where you create a user without the password and then try to set it during user update.

**Comment by bogdanprodan-okta** [comment]
Hi, @thekbb! I don't think this flow is going to work. If you create a user without a password, Okta sends an activation email and the user is the one who sets the password. 
In order to change it from terraform, I need to add `old_password` to the terraform, so you get that password from the user, set that to `old_password`, and set a new value into `password`. The problem is that it might be confusing for the community how this should work. 
The only thing I can think of is to add a check for password check. If user status is `PROVISIONED`, you can not set a new password, because the old password doesn't exist.

**Comment by MichaelOtte-lhsystems** [comment]
Hi @bogdanprodan-okta  why the password cant be set without old_password like  https://developer.okta.com/docs/reference/api/users/#request-example-19

curl -v -X POST \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-H "Authorization: SSWS ${api_token}" \
-d '{
  "credentials": {
    "password" : { "value": "uTVM,TPw55" }
  }
}' "https://${yourOktaDomain}/api/v1/users/00ub0oNGTSWTBKOLGLNR"

**Comment by monde** [comment]
@MichaelOtte-lhsystems can you provide with an example Terraform config so I can see what you are trying to accomplish. Also, if you run terraform with TF_LOG=1 to enable logging you can see what the actual data in the HTTP requests and responses. It might be good to see those, scrub out private information before posting anything.

**Comment by monde** [comment]
Actually, @MichaelOtte-lhsystems can you please open a new issue with the debugging information I've asked for? I see you've commented on a other closed issues. Thanks.

**Comment by MichaelOtte-lhsystems** [comment]
> Actually, @MichaelOtte-lhsystems can you please open a new issue with the debugging information I've asked for? I see you've commented on a other closed issues. Thanks.

Hope that explains its well https://github.com/okta/terraform-provider-okta/issues/1060
