### ISSUE TITLE
Improve Group Rule handling for managing large amount of group rules

### ISSUE THREAD

**Issue by stmyers** [okta/terraform-provider-okta#906]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We recently started migrating all our group rules to be terraform managed.  We're up to 259 group rules in the same repo and now that we have these in TF, each subsequent plan (even speculative) causes a rate limit violation against the /api/v1/groups endpoint (500 limit) and it looks up each group rule individually to look for changes.

Is it possible to change the behavior of the resource using `ListGroupRules` rather than `GetGroupRule`?  

### New or Affected Resource(s)

- okta_group_rule

### References
https://developer.okta.com/docs/reference/api/groups/#list-group-rules

**Comment by monde** [comment]
hi @stmyers apologies for the slow reply. Can you try turning on rating limiting in your provider config [`max_api_capacity`](https://registry.terraform.io/providers/okta/okta/latest/docs#max_api_capacity) . Start out with it trying 75% `max_api_capacity=75`. Let me know if this gets you past the rate limiting issue you have experienced.

**Comment by stmyers** [comment]
> hi @stmyers apologies for the slow reply. Can you try turning on rating limiting in your provider config [`max_api_capacity`](https://registry.terraform.io/providers/okta/okta/latest/docs#max_api_capacity) . Start out with it trying 75% `max_api_capacity=75`. Let me know if this gets you past the rate limiting issue you have experienced.

That's actually exactly what I ended up doing to solve this for now - it has removed the rate limit violations.

To speed up plan/apply activity, I've also restructured the repo where possible so that fewer rules are managed in the same state file.

**Comment by monde** [comment]
@stmyers I'm also looking into another ask from a customer to add a skip flag on to resources to prevent additional information fetches. I'll keep this in mind along with that work on keep you posted.

**Comment by ymylei** [comment]
IMO using `ListGroupRules` vs `GetGroupRule` won't matter here:


When handling the individual resource, the various operations are going to be for those individually. ListRules would only be useful if the cache was also turned on, otherwise reach group_rule resource would call ListRules for each run. The issue with the caching, and why it's turned off by default on most terraform providers, is it can mess up the handling of create, update, and delete operations which are checking (via a List or Get, either directly or with a call to the Read function) on the state of the object post change.

Hacky stuff like the caching things I mentioned could be useful, but it would be better for both parties in the equation (developers and users of the provider) if instead Okta provided higher API capacity for organisations that need it.

**Comment by monde** [comment]
Okta internal reference: https://oktainc.atlassian.net/browse/OKTA-544487
