### ISSUE TITLE
okta_group: removal failure because of policy resource

### ISSUE THREAD

**Issue by jaimellamasi** [okta/terraform-provider-okta#99]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
NXT-C02V60SCHV2F:Desktop jllamas$ terraform -v
Terraform v0.11.14
+ provider.okta v3.1.1
```
I tried with most recent terraform version 0.12.24 and the problem persists.

### Affected Resource(s)

* okta_group
* okta_auth_server_policy

### Terraform Configuration Files

Terraform file: https://gist.github.com/jllamasi/e299cbd3ede866f6eb7f49ce851f2a54

### Debug Output

```
okta_auth_server.default: Refreshing state... (ID: ausej54t1mAeuDsrk0x6)
okta_group.customer_group: Refreshing state... (ID: 00gej5dx94UaZL8F00x6)
okta_app_oauth.customer_oauth_app: Refreshing state... (ID: 0oaej5c9fW9MK93ds0x6)
okta_auth_server_scope.customer_scope: Refreshing state... (ID: scpej5khjLCNk97Ui0x6)
okta_auth_server_policy.customer_policy: Refreshing state... (ID: 00pej5iwfT5TyzEEj0x6)
okta_auth_server_scope.customer_scope: Destroying... (ID: scpej5khjLCNk97Ui0x6)
okta_auth_server_policy.customer_policy: Destroying... (ID: 00pej5iwfT5TyzEEj0x6)
okta_group.customer_group: Destroying... (ID: 00gej5dx94UaZL8F00x6)
okta_auth_server_scope.customer_scope: Destruction complete after 1s
okta_auth_server_policy.customer_policy: Destruction complete after 1s
okta_app_oauth.customer_oauth_app: Destroying... (ID: 0oaej5c9fW9MK93ds0x6)
okta_auth_server.default: Destroying... (ID: ausej54t1mAeuDsrk0x6)
okta_app_oauth.customer_oauth_app: Destruction complete after 0s
okta_auth_server.default: Destruction complete after 0s

Error: Error applying plan:

1 error occurred:
	* okta_group.customer_group (destroy): 1 error occurred:
	* okta_group.customer_group: The API returned an error: Not found: Resource not found: 00pej5iwfT5TyzEEj0x6 (Policy)
```

DEBUG log:
https://gist.github.com/jllamasi/f8808d786089949b6ac79dc95d0f7db4

### Expected Behavior

All resources are removed and terraform does not throw any error **consistently**.

### Actual Behavior

okta provider ```destroy``` action is **randomly** failed because of a "404 Not Found" error is thrown by Okta when trying to remove a Policy. The super weird thing here is that sometimes happens and sometimes not. Also, the error output seems to be misleading, as it indicates okta_group cannot be removed, when it's actually the policy resource.

If you try to ```destroy``` for a second time, then you will get that there's nothing to destroy and terraform ends OK. So, behinds the scenes, the provider destroys everything you need to be destroyed, but there's something wrong with the provider when is trying to remove a resource that seems to be already destroyed

### Steps to Reproduce

1. ```terraform init```

2. ```terraform apply -var=okta_api_token=$OKTA_TOKEN -var=okta_base_url=$OKTA_BASE_URL -var=okta_org_name=$OKTA_ORG_NAME```
3. ```terraform destroy -var=okta_api_token=$OKTA_TOKEN -var=okta_base_url=$OKTA_BASE_URL -var=okta_org_name=$OKTA_ORG_NAME```

**Comment by aaronjohnstone-okta** [comment]
To fix this add 'depends_on =  okta_auth_server.default' to your auth server scope and policy resources.

The reason for the error is due to the auth server policy attempting to be deleted after the auth server itself has been deleted. This is due to the multi-threaded nature of Terraform. This is also the reason it is random, in some cases it the scope and policy threads will run before the auth server is deleted.
It is pretty good at working out dependencies during create. In your scenario, the 'okta_auth_server.default.id' is used in the customer_policy. So it ensures that dependency is met when creating. 
It is more difficult to work that out on the destroy. If you add the depends_on TF will ensure the scope and policy are removed before the auth server. 
Disclaimer - I don't work on the plugin development.

**Comment by jaimellamasi** [comment]
Hello @aaronjohnstone-okta , thanks for your response. I do not think this is error, as I actually got the `auth_server` information from a remote state in the cloud, so it's not part of the destroy plan. I just put it as a new resource in my gist for demonstration purposes.

**Comment by noinarisak** [comment]
Hi @jllamasi,

I believe @aaronjohnstone-okta might be on the right track when it comes to `Not found: Resource not found` error. You could test with `depends_on` as @aaronjohnstone-okta mention so the execution has to wait before performing another HTTP call. Another possible option is to prevent the default concurrent calls in your `destroy` with the "[-paralelism=1](https://www.terraform.io/docs/commands/apply.html#parallelism-n)" option. Note: This will slow things down though. I prefer the `depends_on` option because it is less disruptive and it keeps the `apply` and `destroy` command shorter. 😄 

The inconsistency is probably due to how Terraform walks up the graph more details [here](https://www.terraform.io/docs/internals/graph.html#walking-the-graph).

Can you give one of the options a try?

**Comment by jaimellamasi** [comment]
Hi @noinarisak and thanks for your help. I cannot rely on `depends_on` as my auth server is actually on a remote state (it's not been destroyed on each action) and terraform itself does not allow to do this: `Error: okta_auth_server_policy.customer_policy: depends on value cannot contain interpolations: ${data.terraform_remote_state.okta.default}`

I have tried "-parallelism=1" option and it seems to be a good workaround for this as I'm not performing many resources destruction, although I still do not understand why it's not working as expected without this option.

Thanks for your help!

**Comment by bogdanprodan-okta** [comment]
Hi @jllamasi! I run the steps you've described, and couldn't reproduce this issue using the latest terraform provider. If the problem still exists, please comment here so I can reopen this issue.
